### ISSUE TITLE
vue 3.3.3 not working

### ISSUE THREAD

**Issue by fabry24** [shrpne/vue-inline-svg#58] opened 2023-05-19 06:12 UTC
Hello,
When I change version of vue to 3.3.3, vue-inline-library stop working.
`<InlineSvg :src="require('./assets/arrow.svg')" />` throws error like

![image](https://github.com/shrpne/vue-inline-svg/assets/78112061/c1de5e45-239f-4c49-b224-be2a4226821b)

I have basic vue-cli app with only one library (vue-inline-svg) and with vue version 3.3.3

Could you inspect this problem?

Thank you.

**Comment by nikriaz** [comment] 2023-07-05 14:26
Problem is confirmed also in Vue 3.3.4.

UPD: Resolved by updating to version vue-inline-svg 3.1.2. Mine was limited to the major version 2 in the package.json. Version 2 uses `render(createElement )` which is deprecated in Vue 3 but worked for some reason till Vue 3.2.x

**Comment by shrpne** [comment] 2024-06-10 22:34
@nikriaz thank you, i agree that it is probably caused by incompatible versions, vue@2 should be used with vue-inline-svg@2 and vue@3 should be used with vue-inline-svg@3

**Closed as completed by shrpne** 2024-06-10 22:34 UTC
